/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbc.program;

/**
 *  File: MainUI.java
 *  Desc: Main UI fi8le
 */
public class MainUI extends javax.swing.JFrame {
//    some stuffs
    jdbc.service.MySQLMahasiswaService service = new jdbc.service.MySQLMahasiswaService();
    javax.swing.DefaultListModel<String> idModel = new javax.swing.DefaultListModel<>();
    javax.swing.DefaultListModel<String> nameModel = new javax.swing.DefaultListModel<>();
    int currentIndex = 0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainUI.class.getName());

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        idListShow.setModel(idModel);
        nameListShow.setModel(nameModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idLabelOne = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        idListShow = new javax.swing.JList<>();
        nameLabelOne = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        nameListShow = new javax.swing.JList<>();
        studentDatasLabel = new javax.swing.JLabel();
        getAllDatasButton = new javax.swing.JButton();
        nameLabelThree = new javax.swing.JLabel();
        addNameField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        idLabelTwo = new javax.swing.JLabel();
        editIDField = new javax.swing.JTextField();
        editNameField = new javax.swing.JTextField();
        nameLabelTwo = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        delIDField = new javax.swing.JTextField();
        delNameField = new javax.swing.JTextField();
        delButton = new javax.swing.JButton();
        resetIndexButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idLabelOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idLabelOne.setText("ID");

        idListShow.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(idListShow);

        nameLabelOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabelOne.setText("Name");

        nameListShow.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(nameListShow);

        studentDatasLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentDatasLabel.setText("Student Datas");

        getAllDatasButton.setText("Get All Datas");
        getAllDatasButton.addActionListener(this::getAllDatasButtonActionPerformed);

        nameLabelThree.setText("Name:");

        addNameField.addActionListener(this::addNameFieldActionPerformed);

        addButton.setText("Add");
        addButton.addActionListener(this::addButtonActionPerformed);

        idLabelTwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idLabelTwo.setText("ID");

        editIDField.addActionListener(this::editIDFieldActionPerformed);

        editNameField.addActionListener(this::editNameFieldActionPerformed);

        nameLabelTwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabelTwo.setText("Name");

        editButton.setText("Edit");
        editButton.addActionListener(this::editButtonActionPerformed);

        delIDField.addActionListener(this::delIDFieldActionPerformed);

        delNameField.addActionListener(this::delNameFieldActionPerformed);

        delButton.setText("Del");
        delButton.addActionListener(this::delButtonActionPerformed);

        resetIndexButton.setText("Reset Index");
        resetIndexButton.addActionListener(this::resetIndexButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(idLabelOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nameLabelOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addButton)
                            .addComponent(nameLabelThree)
                            .addComponent(getAllDatasButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(studentDatasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resetIndexButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(delIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(delNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(editIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(idLabelTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nameLabelTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(editNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabelOne)
                    .addComponent(nameLabelOne)
                    .addComponent(studentDatasLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(getAllDatasButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameLabelThree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idLabelTwo)
                            .addComponent(nameLabelTwo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(resetIndexButton))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getAllDatasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAllDatasButtonActionPerformed
        idModel.clear();
        nameModel.clear();
        java.util.List<jdbc.model.Mahasiswa> list = service.getAll();
        
        for (jdbc.model.Mahasiswa m : list) {
            idModel.addElement(String.valueOf(m.getId()));
            nameModel.addElement(m.getName());
            
            if (m.getId() > currentIndex) {
                currentIndex = m.getId();
            }
        }
    }//GEN-LAST:event_getAllDatasButtonActionPerformed

    private void addNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNameFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String name = addNameField.getText().trim();
        
        if (!name.isEmpty()) {
            currentIndex++;
            
            jdbc.model.Mahasiswa m = new jdbc.model.Mahasiswa(currentIndex, name);
            
            service.add(m);
            idModel.addElement(String.valueOf(currentIndex));
            nameModel.addElement(name);
            addNameField.setText("");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void editIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editIDFieldActionPerformed

    private void editNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editNameFieldActionPerformed

    private void delIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delIDFieldActionPerformed

    private void delNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delNameFieldActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        String idText = editIDField.getText().trim();
        String newName = editNameField.getText().trim();
        
        if (!idText.isEmpty() && !newName.isEmpty()) {
            int id = Integer.parseInt(idText);
            jdbc.model.Mahasiswa m = new jdbc.model.Mahasiswa(id, newName);
            
            service.update(m);
            getAllDatasButtonActionPerformed(evt);
            editIDField.setText("");
            editNameField.setText("");
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        String idText = delIDField.getText().trim();
        
        if (!idText.isEmpty()) {
            int id = Integer.parseInt(idText);
            
            service.delete(id);
            getAllDatasButtonActionPerformed(evt);
            delIDField.setText("");
            delNameField.setText("");
        }
    }//GEN-LAST:event_delButtonActionPerformed

    private void resetIndexButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetIndexButtonActionPerformed
        currentIndex = 0;
    }//GEN-LAST:event_resetIndexButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField addNameField;
    private javax.swing.JButton delButton;
    private javax.swing.JTextField delIDField;
    private javax.swing.JTextField delNameField;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField editIDField;
    private javax.swing.JTextField editNameField;
    private javax.swing.JButton getAllDatasButton;
    private javax.swing.JLabel idLabelOne;
    private javax.swing.JLabel idLabelTwo;
    private javax.swing.JList<String> idListShow;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nameLabelOne;
    private javax.swing.JLabel nameLabelThree;
    private javax.swing.JLabel nameLabelTwo;
    private javax.swing.JList<String> nameListShow;
    private javax.swing.JButton resetIndexButton;
    private javax.swing.JLabel studentDatasLabel;
    // End of variables declaration//GEN-END:variables
}
