import javax.swing.DefaultListModel;

/**
 *  File: GUI_3.java
 *  Desc: GUI 3
 */
public class GUI_3 extends javax.swing.JFrame {
//    some stuffs
    javax.swing.DefaultListModel<String> dlm;
    java.util.List<String> listCollection = new java.util.ArrayList<>();
    java.util.Set<String> setCollection = new java.util.HashSet<>();
    java.util.Map<String, String> mapCollection = new java.util.HashMap<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI_3.class.getName());

    /**
     * Creates new form GUI_3
     */
    public GUI_3() {
        initComponents();
        dlm = new javax.swing.DefaultListModel<>();
        listOfThings.setModel(dlm);
        exceptionLabelOutput.setForeground(java.awt.Color.RED);
        exceptionLabelOutput.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listOfThings = new javax.swing.JList<>();
        saveToListButton = new javax.swing.JButton();
        insertDataList = new javax.swing.JButton();
        saveToSetButton = new javax.swing.JButton();
        savedDataLabelSet = new javax.swing.JLabel();
        savedDataLabelList = new javax.swing.JLabel();
        insertDataSet = new javax.swing.JButton();
        savedDataLabelMap = new javax.swing.JLabel();
        saveToMapButton = new javax.swing.JButton();
        insertDataMap = new javax.swing.JButton();
        itemNameLabel = new javax.swing.JLabel();
        textFieldInput = new javax.swing.JTextField();
        clearAllButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        exceptionLabelOutput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listOfThings.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listOfThings);

        saveToListButton.setText("Save to List");
        saveToListButton.addActionListener(this::saveToListButtonActionPerformed);

        insertDataList.setText("Insert Data to List");
        insertDataList.addActionListener(this::insertDataListActionPerformed);

        saveToSetButton.setText("Save to Set");
        saveToSetButton.addActionListener(this::saveToSetButtonActionPerformed);

        savedDataLabelSet.setText("Saved Data:");

        savedDataLabelList.setText("Saved Data:");

        insertDataSet.setText("Insert Data to Set");
        insertDataSet.addActionListener(this::insertDataSetActionPerformed);

        savedDataLabelMap.setText("Saved Data:");

        saveToMapButton.setText("Save to Map");
        saveToMapButton.addActionListener(this::saveToMapButtonActionPerformed);

        insertDataMap.setText("Insert Data to Map");
        insertDataMap.addActionListener(this::insertDataMapActionPerformed);

        itemNameLabel.setText("Item Name");

        textFieldInput.addActionListener(this::textFieldInputActionPerformed);

        clearAllButton.setText("Clear all");
        clearAllButton.addActionListener(this::clearAllButtonActionPerformed);

        addButton.setText("Add");
        addButton.addActionListener(this::addButtonActionPerformed);

        updateButton.setText("Update");
        updateButton.addActionListener(this::updateButtonActionPerformed);

        deleteButton.setText("Delete");
        deleteButton.addActionListener(this::deleteButtonActionPerformed);

        exceptionLabelOutput.setText("Error");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(clearAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveToListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(insertDataList))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveToSetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(insertDataSet))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveToMapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(insertDataMap))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(savedDataLabelSet)
                                .addComponent(savedDataLabelMap)
                                .addComponent(savedDataLabelList)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(itemNameLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(textFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(exceptionLabelOutput))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addButton)
                                .addGap(18, 18, 18)
                                .addComponent(updateButton)
                                .addGap(18, 18, 18)
                                .addComponent(deleteButton)
                                .addGap(17, 17, 17)))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(savedDataLabelList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveToListButton)
                            .addComponent(insertDataList))
                        .addGap(18, 18, 18)
                        .addComponent(savedDataLabelSet)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveToSetButton)
                            .addComponent(insertDataSet))
                        .addGap(18, 18, 18)
                        .addComponent(savedDataLabelMap)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveToMapButton)
                            .addComponent(insertDataMap))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemNameLabel)
                            .addComponent(textFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(exceptionLabelOutput))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearAllButton)
                    .addComponent(addButton)
                    .addComponent(updateButton)
                    .addComponent(deleteButton))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveToListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToListButtonActionPerformed
        listCollection.clear();
        
        for (int i = 0; i < dlm.getSize(); i++) {
            listCollection.add(dlm.getElementAt(i));
        }
        
        savedDataLabelList.setText("Saved Data: " + listCollection.size());
        
        exceptionLabelOutput.setText("");
    }//GEN-LAST:event_saveToListButtonActionPerformed

    private void insertDataListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertDataListActionPerformed
        if (!listCollection.isEmpty()) {
            for (String item : listCollection) {
                dlm.addElement(item);
            }
            
            exceptionLabelOutput.setText("");
        } else {
            exceptionLabelOutput.setText("No data in the list smh");
        }
    }//GEN-LAST:event_insertDataListActionPerformed

    private void saveToSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToSetButtonActionPerformed
        setCollection.clear();
        
        for (int i = 0; i < dlm.getSize(); i++) {
            setCollection.add(dlm.getElementAt(i));
        }
        
        savedDataLabelSet.setText("Saved Data: " + setCollection.size());
        exceptionLabelOutput.setText("");
    }//GEN-LAST:event_saveToSetButtonActionPerformed

    private void insertDataSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertDataSetActionPerformed
        if (!setCollection.isEmpty()) {
            for (String item : setCollection) {
                dlm.addElement(item);
            }
            
            exceptionLabelOutput.setText("");
        } else {
            exceptionLabelOutput.setText("No data in the set smh");
        }
    }//GEN-LAST:event_insertDataSetActionPerformed

    private void saveToMapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToMapButtonActionPerformed
        mapCollection.clear();
        
        for (int i = 0; i < dlm.getSize(); i++) {
            mapCollection.put("item" + i, dlm.getElementAt(i));
        }
        
        savedDataLabelMap.setText("Saved Data: " + mapCollection.size());
        exceptionLabelOutput.setText("");
    }//GEN-LAST:event_saveToMapButtonActionPerformed

    private void insertDataMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertDataMapActionPerformed
        if (!mapCollection.isEmpty()) {
            for (String value : mapCollection.values()) {
                dlm.addElement(value);
            }
            
            exceptionLabelOutput.setText("");
        } else {
            exceptionLabelOutput.setText("No data in the map smh");
        }
    }//GEN-LAST:event_insertDataMapActionPerformed

    private void textFieldInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldInputActionPerformed

    private void clearAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllButtonActionPerformed
        dlm.clear();
        exceptionLabelOutput.setText("");
    }//GEN-LAST:event_clearAllButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (!textFieldInput.getText().isEmpty()) {
            dlm.addElement(textFieldInput.getText());
            
            textFieldInput.setText("");
            
            exceptionLabelOutput.setText("");
        } else {
            exceptionLabelOutput.setText("Enter the name");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        int index = listOfThings.getSelectedIndex();
        
        if (index == -1) {
            exceptionLabelOutput.setText("Select an item to update bruv");
        } else if (textFieldInput.getText().isEmpty()) {
            exceptionLabelOutput.setText("Enter the new name :0");
        } else {
            dlm.setElementAt(textFieldInput.getText(), index);
            textFieldInput.setText("");
            exceptionLabelOutput.setText("");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int index = listOfThings.getSelectedIndex();
        
        if (index != -1) {
            dlm.removeElementAt(index);
            textFieldInput.setText("");
            exceptionLabelOutput.setText("");
        } else {
            exceptionLabelOutput.setText("Select something from the list");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI_3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton clearAllButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel exceptionLabelOutput;
    private javax.swing.JButton insertDataList;
    private javax.swing.JButton insertDataMap;
    private javax.swing.JButton insertDataSet;
    private javax.swing.JLabel itemNameLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listOfThings;
    private javax.swing.JButton saveToListButton;
    private javax.swing.JButton saveToMapButton;
    private javax.swing.JButton saveToSetButton;
    private javax.swing.JLabel savedDataLabelList;
    private javax.swing.JLabel savedDataLabelMap;
    private javax.swing.JLabel savedDataLabelSet;
    private javax.swing.JTextField textFieldInput;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
