import javax.swing.DefaultListModel;

/**
 *  File: GUI_2.java
 *  Desc: GUI 2
 */

public class GUI_2 extends javax.swing.JFrame {
    javax.swing.DefaultListModel<String> dlm;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI_2.class.getName());

    /**
     * Creates new form GUI_2
     */
    public GUI_2() {
        initComponents();
        dlm = new javax.swing.DefaultListModel<>();
        listOfThings1.setModel(dlm);
        errorMessageLabel.setForeground(java.awt.Color.RED);
        errorMessageLabel.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listOfThings1 = new javax.swing.JList<>();
        insertDataButtonOne = new javax.swing.JButton();
        itemNameLabelOne = new javax.swing.JLabel();
        textFieldOne = new javax.swing.JTextField();
        addButtonOne = new javax.swing.JButton();
        updateButtonOne = new javax.swing.JButton();
        deleteButtonOne = new javax.swing.JButton();
        clearAllButtonOne = new javax.swing.JButton();
        errorMessageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listOfThings1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listOfThings1);

        insertDataButtonOne.setText("Insert Data");
        insertDataButtonOne.addActionListener(this::insertDataButtonOneActionPerformed);

        itemNameLabelOne.setText("Item Name");

        textFieldOne.addActionListener(this::textFieldOneActionPerformed);

        addButtonOne.setText("Add");
        addButtonOne.addActionListener(this::addButtonOneActionPerformed);

        updateButtonOne.setText("Update");
        updateButtonOne.addActionListener(this::updateButtonOneActionPerformed);

        deleteButtonOne.setText("Delete");
        deleteButtonOne.addActionListener(this::deleteButtonOneActionPerformed);

        clearAllButtonOne.setText("Clear all");
        clearAllButtonOne.addActionListener(this::clearAllButtonOneActionPerformed);

        errorMessageLabel.setText("Error Message:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(itemNameLabelOne)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldOne)
                                .addGap(15, 15, 15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(insertDataButtonOne)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(deleteButtonOne, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addComponent(addButtonOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(updateButtonOne, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clearAllButtonOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(errorMessageLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(insertDataButtonOne)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemNameLabelOne)
                            .addComponent(textFieldOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButtonOne)
                            .addComponent(updateButtonOne))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearAllButtonOne)
                            .addComponent(deleteButtonOne))))
                .addGap(18, 18, 18)
                .addComponent(errorMessageLabel)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertDataButtonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertDataButtonOneActionPerformed
        String[] items = {"buku", "meja", "kursi", "tas", "pintu"};
        
        for (String item : items) {
            dlm.addElement(item);
        }
    }//GEN-LAST:event_insertDataButtonOneActionPerformed

    private void addButtonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonOneActionPerformed
        if (!textFieldOne.getText().isEmpty()) {
            dlm.addElement(textFieldOne.getText());
            textFieldOne.setText("");
            errorMessageLabel.setText("");
        } else {
            errorMessageLabel.setText("Enter something");
        }
    }//GEN-LAST:event_addButtonOneActionPerformed

    private void updateButtonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonOneActionPerformed
        int index = listOfThings1.getSelectedIndex();
        
        if (index == -1) {
            errorMessageLabel.setText("Select an item");
        } else if (textFieldOne.getText().isEmpty()) {
            errorMessageLabel.setText("And enter a new name");
        } else {
            dlm.setElementAt(textFieldOne.getText(), index);
            textFieldOne.setText("");
            errorMessageLabel.setText("");
        }
    }//GEN-LAST:event_updateButtonOneActionPerformed

    private void deleteButtonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonOneActionPerformed
        int index = listOfThings1.getSelectedIndex();
        
        if (index != -1) {
            dlm.removeElementAt(index);
            textFieldOne.setText("");
            errorMessageLabel.setText("");
        } else {
            errorMessageLabel.setText("Click something from the list man");
        }
    }//GEN-LAST:event_deleteButtonOneActionPerformed

    private void clearAllButtonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllButtonOneActionPerformed
        dlm.clear();
    }//GEN-LAST:event_clearAllButtonOneActionPerformed

    private void textFieldOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldOneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI_2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButtonOne;
    private javax.swing.JButton clearAllButtonOne;
    private javax.swing.JButton deleteButtonOne;
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JButton insertDataButtonOne;
    private javax.swing.JLabel itemNameLabelOne;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listOfThings1;
    private javax.swing.JTextField textFieldOne;
    private javax.swing.JButton updateButtonOne;
    // End of variables declaration//GEN-END:variables
}
